project: 
 type: website

website: 
  title: "Heat and Occupation"
  navbar: 
    left: 
    - text: "Home"
      href: index.qmd
    - text: "Heat and Occupation"
      href: heat_and_occupation.qmd
    - text: "About"
      href: about.qmd
    - text: "Resources"
      href: resources.qmd
    - text: "Methods"
      href: methods.qmd
format: 
  html:
    theme: sandstone
    css: "assets_css/styles.css"
  