project: 
 type: website

website: 
  title: "Heat and Occupation"
  back-to-top-navigation: true
  navbar: 
    search: true 
    logo: "images/socalcoshlogo.jpg"
    left: 
    - text: "Home"
      href: index.qmd
    - text: "Heat and Occupation"
      href: heat_and_occupation.qmd
    - text: "About"
      href: about.qmd
    - text: "Resources"
      href: resources.qmd
    - text: "Methods"
      href: methods.qmd
   
format: 
  html:
    theme: sandstone
    css: "assets_css/styles.css"
    grid:
      body-width: 900px
    toc: true
     
  